services:
  - type: web
    name: mobile-chatbot
    runtime: python
    buildCommand: pip install --only-binary=numpy,scipy,scikit-learn -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16