services:
  - type: web
    name: ecommerce-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /app/credentials.json
    files:
      - name: credentials.json
        contents: |
          # Your credentials.json content will be here
          # Make sure to replace this with your actual credentials
